Add AInlineLoading
IBM/carbon-ui-builder pull request #128
Opened 2022-07-21 18:31 UTC by MoizMasud

closes https://github.com/IBM/carbon-ui-builder/issues/122

2022-07-27 12:57 UTC, zvonimirfras requested changes

2022-07-27 12:57 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +		<legend className="bx--label">Status</legend>
Use single quotes everywhere. I think the only place we use double is in exports and that's because of wrapping quotes in quotes.

2022-07-27 12:57 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +		</RadioButtonGroup>
Follow the indentation pattern from the rest of the code base and put the closing `/>` on the same line.

2022-07-27 12:57 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +	type: 'inlineloading',
```suggestion
	type: 'inline-loading',
```

and elsewhere where it's missing...

2022-07-27 12:57 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +		type: 'inlineloading',
```suggestion
		type: 'inline-loading',
```

2022-07-27 12:57 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +							${json.status === 'error' ? `[errorText]="'${json.textDescription}'"`: ''}
This won't work dynamically...

2022-07-27 12:57 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +							${json.status === 'error' ? `[errorText]="'${json.textDescription}'"`: ''}
Should there be 3 inputs in UI?

2022-07-27 12:57 UTC, zvonimirfras commented on src/fragment-components/index.ts
> +import * as inlineloading from './a-inline-loading';
```suggestion
import * as inlineLoading from './a-inline-loading';
```

etc

2022-07-27 12:57 UTC, zvonimirfras commented on src/fragment-components/index.ts
> +	inlineloading,
```suggestion
	inlineLoading,
```

2022-07-27 12:57 UTC, zvonimirfras commented on src/ui-fragment/src/components/ui-inline-loading.tsx
> +	if (state.type !== 'inlineloading') {
```suggestion
	if (state.type !== 'inline-loading') {
```

2022-07-27 12:57 UTC, zvonimirfras commented on src/ui-fragment/src/utils.tsx
> +		case 'inlineloading':
```suggestion
		case 'inline-loading':
```

2022-07-29 13:40 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +		</RadioButtonGroup>
```suggestion
		<RadioButtonGroup
		orientation='vertical'
		name='status-radio-buttons'
		valueSelected={selectedComponent.status}
		onChange={(event: any) => setComponent({
			...selectedComponent,
			status: event
		})}>
			<RadioButton
				id='inactive'
				labelText='Inactive'
				value='inactive' />
			<RadioButton
				id='active'
				labelText='Active'
				value='active' />
			<RadioButton
				id='finished'
				labelText='Finished'
				value='finished' />
			<RadioButton
				id='error'
				labelText='Error'
				value='error' />
		</RadioButtonGroup>
```

sigh

2022-07-29 19:24 UTC, zvonimirfras requested changes
Pros and cons of having all the angular inputs available in UI and then worked around in react export?

2022-07-29 21:29 UTC, MoizMasud commented on src/fragment-components/a-inline-loading.tsx
> +							${json.status === 'error' ? `[errorText]="${nameStringToVariableString(json.codeContext?.name)}ErrorText"`: ''}
angular requires a different input for each type of state. where as react uses `status` input and `description` to take care of state and text of each state.

2022-09-23 18:09 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +							${json.status === 'error' ? `[errorText]="${nameStringToVariableString(json.codeContext?.name)}ErrorText"`: ''}
Sure... Doing this will make it impossible to have any other state except the one it's in at the time of code generation.

2022-11-29 21:17 UTC, Akshat55 commented on src/fragment-components/a-inline-loading.tsx
> +					})}
@zvonimirfras 

I know for a fact this isn't correct, the idea behind on success is to call a function when status is `finished`. But the users are controlling the status, so I don't see a reason in having this onSuccess function at all, should we just remove it or do a check where we expect users will be passing in a function to execute on `finished`?

Other then this one change, this PR looks good to me, let me know what you think we should do here.

2022-12-01 15:24 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +		})} >
```suggestion
		})}>
```

2022-12-01 15:27 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +	return (
```suggestion

	return (
```

2022-12-06 20:36 UTC, Akshat55 requested changes

2022-12-06 20:36 UTC, Akshat55 commented on src/fragment-components/a-inline-loading.tsx
> +					})}
```suggestion
					onSuccess={() => {
						if(typeof state.${nameStringToVariableString(json.codeContext?.name)}OnSuccess === "function") {
							return state.${nameStringToVariableString(json.codeContext?.name)}OnSuccess;
						}
						return undefined;
					})}
```

2022-12-06 20:36 UTC, Akshat55 commented on src/fragment-components/a-inline-loading.tsx
> +					})}
If a function is passed by the user then we return the function otherwise undefined

2022-12-07 04:05 UTC, closed without merging