feat: Add missing Accordion attributes for angular
IBM/carbon-ui-builder pull request #195
Opened 2022-11-24 01:53 UTC by MoizMasud

Signed-off-by: Moiz Masud <moizkhan_007@hotmail.com>

closes https://github.com/IBM/carbon-ui-builder/issues/156

2022-11-25 19:23 UTC, Akshat55 requested changes

2022-11-25 19:23 UTC, Akshat55 commented on src/fragment-components/accordion/a-accordion-item.tsx
> +				@Input() ${nameStringToVariableString(json.codeContext?.name)}Disabled = ${json.disabled};`,
Value for disabled is undefined if user does not interact with the disabled checkbox. Add a condition here to check if  `json.disabled` value is undefined: if so, false, else true.

You can also set initial value for `disabled` in `componentInfo`, see other components for example.

2022-11-25 20:35 UTC, Akshat55 approved these changes

2022-11-29 20:03 UTC, zvonimirfras commented on src/fragment-components/accordion/a-accordion-item.tsx
> +				@Input() ${nameStringToVariableString(json.codeContext?.name)}Disabled = ${json.disabled === undefined ? false : json.disabled}`,
Why not `!!json.disabled`?

2022-11-29 20:33 UTC, MoizMasud commented on src/fragment-components/accordion/a-accordion-item.tsx
> +				@Input() ${nameStringToVariableString(json.codeContext?.name)}Disabled = ${json.disabled === undefined ? false : json.disabled}`,
yeah that works aswell, updated!

2022-11-30 19:14 UTC, zvonimirfras approved these changes

2022-11-30 19:14 UTC, merged