Issue#19
IBM/carbon-ui-builder pull request #197
Opened 2022-11-25 06:25 UTC by MoizMasud

Signed-off-by: Moiz Masud <moizkhan_007@hotmail.com>

closes https://github.com/IBM/carbon-ui-builder/issues/19

2022-11-28 18:35 UTC, Akshat55 approved these changes

2022-11-30 16:47 UTC, Akshat55 requested changes

2022-11-30 16:47 UTC, Akshat55 commented on src/fragment-components/a-searchinput.tsx
> +			})} />
```suggestion
		<Checkbox
			labelText='Auto complete'
			id='autoComplete'
			checked={selectedComponent.autocomplete === 'on'}
			onChange={(checked: any) => setComponent({
				...selectedComponent,
				autocomplete: checked ? 'on' : 'off'
			})} />
```

2022-11-30 16:47 UTC, Akshat55 commented on src/fragment-components/a-searchinput.tsx
> +					autoComplete={componentObj.autoComplete}
```suggestion
					autoComplete={componentObj.autocomplete}
```

2022-11-30 16:47 UTC, Akshat55 commented on src/fragment-components/a-searchinput.tsx
> +					autoComplete={componentObj.autoComplete}
```suggestion
					autoComplete={componentObj.autocomplete}
```

2022-11-30 16:47 UTC, Akshat55 commented on src/fragment-components/a-searchinput.tsx
> +		autoComplete: 'off',
```suggestion
		autocomplete: 'off',
```

2022-11-30 16:47 UTC, Akshat55 commented on src/fragment-components/a-searchinput.tsx
> +				@Input() ${nameStringToVariableString(json.codeContext?.name)}Autocomplete = "${json.autoComplete}";
```suggestion
				@Input() ${nameStringToVariableString(json.codeContext?.name)}Autocomplete = "${json.autocomplete}";
```

2022-11-30 16:47 UTC, Akshat55 commented on src/fragment-components/a-searchinput.tsx
> +						autoComplete="${json.autoComplete}"
```suggestion
						autoComplete="${json.autocomplete}"
```

2022-11-30 16:47 UTC, Akshat55 commented on src/fragment-components/a-searchinput.tsx
> +					autoComplete="${json.autoComplete}"
```suggestion
					autoComplete="${json.autocomplete}"
```

2022-11-30 16:47 UTC, Akshat55 commented on src/ui-fragment/src/components/ui-serach-input.tsx
> +			autoComplete={state.autoComplete}
```suggestion
			autoComplete={state.autocomplete}
```

Also change line 10 in this file to use lowercase c so:
```
autocomplete?: string;
```

2022-11-30 16:47 UTC, Akshat55 commented on src/ui-fragment/src/components/ui-serach-input.tsx
> +		autoComplete={state.autoComplete}
```suggestion
		autoComplete={state.autocomplete}
```

2022-11-30 17:38 UTC, Akshat55 approved these changes

2022-11-30 18:38 UTC, Akshat55 requested changes

2022-11-30 18:38 UTC, Akshat55 commented on src/fragment-components/a-searchinput.tsx
> +			id='autoComplete'
```suggestion
			id='autocomplete'
```

2022-11-30 18:39 UTC, Akshat55 approved these changes

2022-11-30 19:19 UTC, zvonimirfras approved these changes

2022-11-30 19:20 UTC, merged