feat: Add inline loading component
IBM/carbon-ui-builder pull request #202
Opened 2022-12-07 04:05 UTC by MoizMasud

Signed-off-by: Moiz Masud <moizkhan_007@hotmail.com>

closes https://github.com/IBM/carbon-ui-builder/issues/122

2022-12-07 19:57 UTC, Akshat55 requested changes

2022-12-07 19:57 UTC, Akshat55 commented on src/fragment-components/a-inline-loading.tsx
> +					})}
```suggestion
					}}
```

Incorrect syntax on export for react

2022-12-08 18:44 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +			label='Success delay'
```suggestion
			label='Success delay (ms)'
```

2022-12-08 18:46 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +			className={componentObj.cssClasses?.map((cc: any) => cc.id).join(' ')} />
```suggestion
				successDelay={componentObj.successDelay}
				description={status[componentObj.status].description}
				iconDescription={status[componentObj.status].iconDescription}
				status={componentObj.status}
				className={componentObj.cssClasses?.map((cc: any) => cc.id).join(' ')} />
```

2022-12-08 18:48 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +		successDelay: 1500
```suggestion
		status: 'active'
```

2022-12-08 18:56 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +				@Input() ${nameStringToVariableString(json.codeContext?.name)}SuccessDelay = ${json.successDelay};`,
```suggestion
				@Input() ${nameStringToVariableString(json.codeContext?.name)}LoadingText = "${json.activeText || 'Loading...'}";
				@Input() ${nameStringToVariableString(json.codeContext?.name)}SuccessText = "${json.successText || 'Finished.'}";
				@Input() ${nameStringToVariableString(json.codeContext?.name)}ErrorText = "${json.errorText || 'Error!'}";
				@Input() ${nameStringToVariableString(json.codeContext?.name)}SuccessDelay = ${json.successDelay === undefined ? 1500 : json.successDelay };`,
```

2022-12-08 18:59 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +						return undefined;
```suggestion
							state.${nameStringToVariableString(json.codeContext?.name)}OnSuccess();
						}
```

2022-12-08 19:00 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +						if(typeof state.${nameStringToVariableString(json.codeContext?.name)}OnSuccess === "function") {
```suggestion
						if (typeof state.${nameStringToVariableString(json.codeContext?.name)}OnSuccess === "function") {
```

2022-12-08 19:01 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +				return {
```suggestion

				return {
```

2022-12-08 20:18 UTC, Akshat55 commented on src/fragment-components/a-inline-loading.tsx
> +							description: "${json.activeText}"
```suggestion
							iconDescription: "${json.activeIconDescription || 'Loading...'}",
							description: "${json.activeText  || 'Loading...'}"
```

2022-12-08 20:20 UTC, Akshat55 commented on src/fragment-components/a-inline-loading.tsx
> +							description: "${json.errorText}"
```suggestion
							iconDescription: "${json.errorIconDescription || 'Error!'}",
							description: "${json.errorText || 'Error!'}"
```

2022-12-08 20:21 UTC, Akshat55 commented on src/fragment-components/a-inline-loading.tsx
> +							description: "${json.inactiveText}"
```suggestion
							iconDescription: "${json.inactiveIconDescription || ''}",
							description: "${json.inactiveText || ''}"
```

2022-12-08 20:22 UTC, Akshat55 commented on src/fragment-components/a-inline-loading.tsx
> +							description: "${json.successText}"
```suggestion
							iconDescription: "${json.finishedIconDescription || 'Finished.'}",
							description: "${json.successText || 'Finished.'}"
```

2022-12-09 14:09 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +	name: 'Inline Loading',
```suggestion
	name: 'Inline loading',
```

2022-12-09 14:16 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +		status: 'active'
```suggestion
		status: 'active',
		activeText: 'Loading...',
		successText: 'Finished.',
		errorText: 'Error!'
```

2022-12-09 14:17 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +				@Input() ${nameStringToVariableString(json.codeContext?.name)}ErrorText = "${json.errorText || 'Error!'}";
```suggestion
				@Input() ${nameStringToVariableString(json.codeContext?.name)}LoadingText = "${json.activeText}";
				@Input() ${nameStringToVariableString(json.codeContext?.name)}SuccessText = "${json.successText}";
				@Input() ${nameStringToVariableString(json.codeContext?.name)}ErrorText = "${json.errorText}";
```

2022-12-09 14:19 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +			value={selectedComponent.successDelay}
```suggestion
			value={selectedComponent.successDelay}
			step={100}
```

2022-12-09 14:19 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +			labelText='Active text description'
```suggestion
			labelText='Active text'
```

2022-12-09 14:19 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +			labelText='Inactive text description'
```suggestion
			labelText='Inactive text'
```

2022-12-09 14:20 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +			labelText='Error text description'
```suggestion
			labelText='Error text'
```

2022-12-09 14:20 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +			labelText='Success text description'
```suggestion
			labelText='Success text'
```

2022-12-09 14:20 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +			labelText='Active icon description'
```suggestion
			labelText='Active icon'
```

2022-12-09 14:45 UTC, zvonimirfras requested changes

2022-12-09 14:45 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +		<TextInput
Put icon descriptions in an "Accessibility" accordion so they don't take that much space on the screen.

They default to the accompanying text anyway and might not even be used.

Put it at the end of the section (after all other settings)

2022-12-09 14:45 UTC, zvonimirfras commented on src/fragment-components/a-inline-loading.tsx
> +		<RadioButtonGroup
Use dropdown instead with active as default.

Users will rarely need to change this.

2023-01-16 15:22 UTC, zvonimirfras approved these changes

2023-01-16 15:22 UTC, merged